disabled_rules: 
- trailing_whitespace
opt_in_rules:
- empty_count
excluded:
- Carthage
- Configuration
- Pods
- vendor

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 120
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 700
  error: 1500
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded:
    - iPhone
    - T
nesting:
  type_level: 3
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - db
    - vm
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
